services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    user: node
    # ports:
    #   - "3000:3000"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G
